Css x path homework
miklashevich/lesson_5 pull request #2
Opened 2021-03-23 06:20 UTC by miklashevich

2021-04-04 13:19 UTC, wildpioneer requested changes

2021-04-04 13:19 UTC, wildpioneer commented on src/test/java/jobsTutByLocators.java
> +
Отсутствует driver.quit

2021-04-04 14:12 UTC, miklashevich commented on src/test/java/jobsTutByLocators.java
> +
добавил driver.quit

2021-04-19 17:32 UTC, wildpioneer commented
Verified

2021-06-04 04:54 UTC, merged